[theme]
base = "dark"
primaryColor = "#FF5C8D"            # Vibrant pink
backgroundColor = "#0F1419"         # Deep blue-black
secondaryBackgroundColor = "#1C2128"
textColor = "#F2F2F2"
font = "sans serif"


