[theme]
# Base
base = "dark"
backgroundColor = "#0F1419"       # Blue-black for a corporate tech feel
secondaryBackgroundColor = "#1C2128"  # Slightly blue-tinted elevation

# Brand Colors
primaryColor = "#00D1B2"         # More teal-leaning primary for professionalism
secondaryColor = "#E6C200"       # Sophisticated gold tone

# Text & Typography
textColor = "#E6E6E6"            # Slightly off-white for less harshness
font = "sans serif"
headerFont = "sans serif"        # Clean headers

# Additional Touches
borderRadius = "0.375rem"        # Balanced corner rounding
shadowSize = "lg"                # Pronounced shadows for depth
spacing = "md"                   # Comfortable spacing between elements
