[theme]
base="dark"

# Brand & Accent Colors
primaryColor = "#00FFD1"         # Neon aqua for buttons and highlights
backgroundColor = "#0D0D0D"      # Rich black background
secondaryBackgroundColor = "#1A1A1A"  # Slightly lighter for cards/containers

# Text Colors
textColor = "#EAEAEA"            # Soft white for main text
font = "sans serif"              # Options: "sans serif", "serif", "monospace"

# Optional: Make widgets pop more
secondaryColor = "#FFD700"       # Gold for secondary buttons/accents
